package com.taipei.iot.audit.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * 審計事件類型。
 * <p>
 * 所有寫入 user_event_log.event_type 的值都必須在此 enum 定義。 {@code @AuditEvent} 與手動呼叫均強制使用此
 * enum，確保編譯期檢查。
 * </p>
 *
 * <p>
 * 新增模組時，在對應的 category 區塊加入新值即可。
 * </p>
 */
@Getter
@RequiredArgsConstructor
public enum AuditEventType {

	// ── USER_AUTH ──
	LOGIN_SUCCESS("LOGIN_SUCCESS", AuditCategory.USER_AUTH, true),
	LOGIN_FAIL("LOGIN_FAIL", AuditCategory.USER_AUTH, false), LOGOUT("LOGOUT", AuditCategory.USER_AUTH, true),
	IDLE_TIMEOUT_LOGOUT("IDLE_TIMEOUT_LOGOUT", AuditCategory.USER_AUTH, true),
	TENANT_SWITCH("TENANT_SWITCH", AuditCategory.USER_AUTH, true),

	// ── ACCOUNT ──
	CREATE_USER("CREATE_USER", AuditCategory.ACCOUNT, true), UPDATE_USER("UPDATE_USER", AuditCategory.ACCOUNT, true),
	DISABLE_USER("DISABLE_USER", AuditCategory.ACCOUNT, true),
	SOFT_DELETE_USER("SOFT_DELETE_USER", AuditCategory.ACCOUNT, true),
	RESTORE_USER("RESTORE_USER", AuditCategory.ACCOUNT, true),

	// ── SYSTEM ──
	CREATE_DEPT("CREATE_DEPT", AuditCategory.SYSTEM, true), UPDATE_DEPT("UPDATE_DEPT", AuditCategory.SYSTEM, true),
	DELETE_DEPT("DELETE_DEPT", AuditCategory.SYSTEM, true), CREATE_MENU("CREATE_MENU", AuditCategory.SYSTEM, true),
	UPDATE_MENU("UPDATE_MENU", AuditCategory.SYSTEM, true), DELETE_MENU("DELETE_MENU", AuditCategory.SYSTEM, true),
	TOGGLE_VISIBLE("TOGGLE_VISIBLE", AuditCategory.SYSTEM, true),
	CREATE_ROLE("CREATE_ROLE", AuditCategory.SYSTEM, true), UPDATE_ROLE("UPDATE_ROLE", AuditCategory.SYSTEM, true),
	TOGGLE_ROLE_ENABLED("TOGGLE_ROLE_ENABLED", AuditCategory.SYSTEM, true),
	ASSIGN_ROLE_PERMISSIONS("ASSIGN_ROLE_PERMISSIONS", AuditCategory.SYSTEM, true),

	// ── PLATFORM / IMPERSONATION (ADR-002) ──
	IMPERSONATE_START("IMPERSONATE_START", AuditCategory.SYSTEM, true),
	IMPERSONATE_END("IMPERSONATE_END", AuditCategory.SYSTEM, true),

	// ── SETTING ──
	UPDATE_SETTING("UPDATE_SETTING", AuditCategory.SYSTEM, true),
	UPDATE_PASSWORD_POLICY("UPDATE_PASSWORD_POLICY", AuditCategory.SYSTEM, true),
	UPDATE_PLATFORM_PASSWORD_POLICY("UPDATE_PLATFORM_PASSWORD_POLICY", AuditCategory.SYSTEM, true),
	// Phase 3：強制改密流程（過期 / 首次登入 / 管理者重設後）
	FORCE_CHANGE_PASSWORD("FORCE_CHANGE_PASSWORD", AuditCategory.SYSTEM, true),

	// ── ANNOUNCEMENT ──
	CREATE_ANNOUNCEMENT("CREATE_ANNOUNCEMENT", AuditCategory.SYSTEM, true),
	UPDATE_ANNOUNCEMENT("UPDATE_ANNOUNCEMENT", AuditCategory.SYSTEM, true),
	DELETE_ANNOUNCEMENT("DELETE_ANNOUNCEMENT", AuditCategory.SYSTEM, true),

	// ── PLATFORM ANNOUNCEMENT ──
	CREATE_PLATFORM_ANNOUNCEMENT("CREATE_PLATFORM_ANNOUNCEMENT", AuditCategory.SYSTEM, true),
	UPDATE_PLATFORM_ANNOUNCEMENT("UPDATE_PLATFORM_ANNOUNCEMENT", AuditCategory.SYSTEM, true),
	DELETE_PLATFORM_ANNOUNCEMENT("DELETE_PLATFORM_ANNOUNCEMENT", AuditCategory.SYSTEM, true),

	// ── ASSET ──
	CREATE_DEVICE("CREATE_DEVICE", AuditCategory.ASSET, true),
	UPDATE_DEVICE("UPDATE_DEVICE", AuditCategory.ASSET, true),
	DELETE_DEVICE("DELETE_DEVICE", AuditCategory.ASSET, true),
	EXPORT_DEVICE("EXPORT_DEVICE", AuditCategory.ASSET, true),
	CREATE_CIRCUIT("CREATE_CIRCUIT", AuditCategory.ASSET, true),
	UPDATE_CIRCUIT("UPDATE_CIRCUIT", AuditCategory.ASSET, true),
	CREATE_CONTRACT("CREATE_CONTRACT", AuditCategory.ASSET, true),
	UPDATE_CONTRACT("UPDATE_CONTRACT", AuditCategory.ASSET, true),

	// ── WORKFLOW ──
	CREATE_ASSET_TRANSFER("CREATE_ASSET_TRANSFER", AuditCategory.WORKFLOW, true),
	WORKFLOW_SUBMIT("WORKFLOW_SUBMIT", AuditCategory.WORKFLOW, true),
	WORKFLOW_APPROVE("WORKFLOW_APPROVE", AuditCategory.WORKFLOW, true),
	WORKFLOW_REJECT("WORKFLOW_REJECT", AuditCategory.WORKFLOW, true),
	WORKFLOW_RESUBMIT("WORKFLOW_RESUBMIT", AuditCategory.WORKFLOW, true),
	WORKFLOW_CANCEL("WORKFLOW_CANCEL", AuditCategory.WORKFLOW, true),
	WORKFLOW_RETURN("WORKFLOW_RETURN", AuditCategory.WORKFLOW, true),
	WORKFLOW_DISPATCH("WORKFLOW_DISPATCH", AuditCategory.WORKFLOW, true),

	// ── MAINTENANCE（報修維護） ──
	CREATE_REPAIR_TICKET("CREATE_REPAIR_TICKET", AuditCategory.MAINTENANCE, true),
	UPDATE_REPAIR_TICKET("UPDATE_REPAIR_TICKET", AuditCategory.MAINTENANCE, true),
	CLOSE_REPAIR_TICKET("CLOSE_REPAIR_TICKET", AuditCategory.MAINTENANCE, true),
	DISPATCH_REPAIR("DISPATCH_REPAIR", AuditCategory.MAINTENANCE, true),
	COMPLETE_REPAIR("COMPLETE_REPAIR", AuditCategory.MAINTENANCE, true),

	// ── MATERIAL（材料管理） ──
	CREATE_PURCHASE_ORDER("CREATE_PURCHASE_ORDER", AuditCategory.MATERIAL, true),
	RECEIVE_MATERIAL("RECEIVE_MATERIAL", AuditCategory.MATERIAL, true),
	ISSUE_MATERIAL("ISSUE_MATERIAL", AuditCategory.MATERIAL, true),
	ADJUST_INVENTORY("ADJUST_INVENTORY", AuditCategory.MATERIAL, true),
	DISPOSE_MATERIAL("DISPOSE_MATERIAL", AuditCategory.MATERIAL, true),
	IMPORT_APPROVED_MATERIAL("IMPORT_APPROVED_MATERIAL", AuditCategory.MATERIAL, true),

	// ── REPLACEMENT（換裝維護） ──
	CREATE_REPLACEMENT_ORDER("CREATE_REPLACEMENT_ORDER", AuditCategory.REPLACEMENT, true),
	UPDATE_REPLACEMENT_ORDER("UPDATE_REPLACEMENT_ORDER", AuditCategory.REPLACEMENT, true),
	SELF_CHECK_REPLACEMENT("SELF_CHECK_REPLACEMENT", AuditCategory.REPLACEMENT, true),
	CLOSE_REPLACEMENT("CLOSE_REPLACEMENT", AuditCategory.REPLACEMENT, true),

	// ── AUDIT ──
	EXPORT_AUDIT("EXPORT_AUDIT", AuditCategory.SYSTEM, true),

	// ── KPI（績效管理） ──
	CREATE_KPI_INDICATOR("CREATE_KPI_INDICATOR", AuditCategory.KPI, true),
	UPDATE_KPI_INDICATOR("UPDATE_KPI_INDICATOR", AuditCategory.KPI, true),
	DELETE_KPI_INDICATOR("DELETE_KPI_INDICATOR", AuditCategory.KPI, true),
	IMPORT_KPI_DATA("IMPORT_KPI_DATA", AuditCategory.KPI, true),
	CALCULATE_KPI("CALCULATE_KPI", AuditCategory.KPI, true),
	LOCK_KPI_PERIOD("LOCK_KPI_PERIOD", AuditCategory.KPI, true),
	UNLOCK_KPI_PERIOD("UNLOCK_KPI_PERIOD", AuditCategory.KPI, true),
	EXPORT_KPI_REPORT("EXPORT_KPI_REPORT", AuditCategory.KPI, true),

	// ── DASHBOARD（儀表板） ──
	UPDATE_DASHBOARD_LAYOUT("UPDATE_DASHBOARD_LAYOUT", AuditCategory.DASHBOARD, true),
	RESET_DASHBOARD_LAYOUT("RESET_DASHBOARD_LAYOUT", AuditCategory.DASHBOARD, true),
	UPDATE_DEFAULT_DASHBOARD_LAYOUT("UPDATE_DEFAULT_DASHBOARD_LAYOUT", AuditCategory.DASHBOARD, true),

	// ── IOT（智慧路燈）Phase 7 ──
	REGISTER_IOT_DEVICE("REGISTER_IOT_DEVICE", AuditCategory.IOT, true),
	CREATE_TELEMETRY_FORMAT("CREATE_TELEMETRY_FORMAT", AuditCategory.IOT, true),
	UPDATE_TELEMETRY_FORMAT("UPDATE_TELEMETRY_FORMAT", AuditCategory.IOT, true),
	SEND_DIMMING_COMMAND("SEND_DIMMING_COMMAND", AuditCategory.IOT, true),
	CREATE_DIMMING_GROUP("CREATE_DIMMING_GROUP", AuditCategory.IOT, true),
	UPDATE_DIMMING_GROUP("UPDATE_DIMMING_GROUP", AuditCategory.IOT, true),
	DELETE_DIMMING_GROUP("DELETE_DIMMING_GROUP", AuditCategory.IOT, true),
	CREATE_DIMMING_SCHEDULE("CREATE_DIMMING_SCHEDULE", AuditCategory.IOT, true),
	UPDATE_DIMMING_SCHEDULE("UPDATE_DIMMING_SCHEDULE", AuditCategory.IOT, true),
	DELETE_DIMMING_SCHEDULE("DELETE_DIMMING_SCHEDULE", AuditCategory.IOT, true),
	CREATE_EVENT_RULE("CREATE_EVENT_RULE", AuditCategory.IOT, true),
	UPDATE_EVENT_RULE("UPDATE_EVENT_RULE", AuditCategory.IOT, true),
	DELETE_EVENT_RULE("DELETE_EVENT_RULE", AuditCategory.IOT, true),
	ACKNOWLEDGE_ALERT("ACKNOWLEDGE_ALERT", AuditCategory.IOT, true),
	RESOLVE_ALERT("RESOLVE_ALERT", AuditCategory.IOT, true), EXPORT_ALERTS("EXPORT_ALERTS", AuditCategory.IOT, true),

	// ── TENANT（場域管理） ──
	CREATE_TENANT("CREATE_TENANT", AuditCategory.TENANT, true),
	UPDATE_TENANT("UPDATE_TENANT", AuditCategory.TENANT, true),
	TOGGLE_TENANT_ENABLED("TOGGLE_TENANT_ENABLED", AuditCategory.TENANT, true),

	// ── NOTIFICATION（通知） ──
	MARK_NOTIFICATION_READ("MARK_NOTIFICATION_READ", AuditCategory.NOTIFICATION, true),
	MARK_ALL_NOTIFICATIONS_READ("MARK_ALL_NOTIFICATIONS_READ", AuditCategory.NOTIFICATION, true),

	// ── SECURITY（檔案掃毒 / 防護事件）[common v2 F-3] ──
	// 用於 SIEM 撈取：當檔案掃毒判定為 INFECTED 或 ERROR 時寫入 audit_log
	FILE_VIRUS_INFECTED("FILE_VIRUS_INFECTED", AuditCategory.SYSTEM, false),
	FILE_SCAN_ERROR("FILE_SCAN_ERROR", AuditCategory.SYSTEM, false),;

	/** 存入 DB 的字串值 */
	private final String value;

	/** 事件分類（對應 user_event_log.event_desc） */
	private final AuditCategory category;

	/** 是否為成功事件（用於決定 errorCode） */
	private final boolean success;

	/** 取得對應的 errorCode */
	public String errorCode() {
		return success ? "00000" : "99999";
	}

}
